### PR TITLE
launch/pepper_full.launch : support nao_port in launch/naoqi_driver.launch https://github.com/ros-naoqi/naoqi_driver/pull/52

### PR DESCRIPTION
**Pull request by k-okada**
this requires https://github.com/ros-naoqi/naoqi_driver/pull/52

### CODE REVIEW

**Comment by vrabaud** [comment]
We shoudl really rename those nao_port and nao_ip to port and ip no ? @suryaambrose ?

**Comment by suryaambrose** [comment]
Don't know. As there is a "roscore_ip" I think it makes sense to prefix all _ip arguments with a name to specify which ip we are talking about. 
But since nao is not the only robot, maybe this can be indeed changed to robot_ip or naoqi_ip ? And then, same change for "nao_port" for consistency ?

**Comment by k-okada** [comment]
+1 for nao_ip or naoqi_ip

## 

◉ Kei Okada

**Comment by vrabaud** [comment]
+1 for naoqi_ip too.

**Pull request merged**
