### PR TITLE
Added pepper_walker which is ported from nao_walker

### PR DESCRIPTION
**Pull request by yoneken**
I created a pepper_walker node which is ported from nao_walker.
This node may be useful to control a pepper with geometry_msgs/Twist.

### CODE REVIEW

**Comment by Karsten1987** [comment]
Hi,

thanks for the work, but please be aware that a /cmd_vel subscription does already exist in naoqi_driver. Have a look at here: https://github.com/ros-naoqi/naoqi_driver/blob/master/src/subscribers/teleop.cpp#L44

**Comment by yoneken** [comment]
Oooops!
Thank you for the comment. I have not noticed it!

**Comment by k-okada** [comment]
I think that is supported via 
https://github.com/ros-naoqi/pepper_robot/blob/master/pepper_bringup/launch/pepper_full_py.launch#L12
-> 
https://github.com/ros-naoqi/naoqi_bridge/blob/master/naoqi_driver_py/launch/naoqi_driver.launch#L23

## 

◉ Kei Okada

**Comment by yoneken** [comment]
Prof. @k-okada , thank you for the reference!
I confirmed the code in a real robot.

**Pull request closed without merging**
