### PR TITLE
Added depth_processing.launch to publish 2 types of pointcloud

### PR DESCRIPTION
**Pull request by robograffitti**
Added depth_processing.launch to publish /pepper_robot/camera/depth/points and /pepper_robot/camera/depth_registered/points.

### CODE REVIEW

**Comment by vrabaud** [comment]
Hi, sorry for the delay: you need to add a runtime dependency on rgbd_launch in the package.xml. Thx.
@suryaambrose, you should look at that repo too.

**Comment by k-okada** [comment]
if this file is just copied from rgdb_launch package or others, then you
need to put comment on that, if it is customized for this robot, we can
remove unnecessary lines, for example kinect_frame.launch.

## 

◉ Kei Okada

**Comment by furushchev** [comment]
overriden by #27

**Comment by mikaelarguedas** [comment]
thanks for the pointer, closing this in favor of #27

**Pull request closed without merging**
