### PR TITLE
[pepper_bringup] add namespace arg to naoqi_driver.launch

### PR DESCRIPTION
**Pull request by kochigami**
I added namespace arg instead of adding it as a group name.
This pull-request is related to https://github.com/ros-naoqi/naoqi_driver/pull/81 .
If there is any problem, please let me know.

The result is like this:
```
roslaunch pepper_bringup pepper_full.launch 
=> 
rosnode list
/pepper_robot
/pepper_robot/camera/bottom_rectify_color
/pepper_robot/camera/camera_nodelet_manager
/pepper_robot/camera/depth_metric
/pepper_robot/camera/depth_metric_rect
/pepper_robot/camera/depth_rectify_depth
/pepper_robot/camera/depth_registered_hw_metric_rect
/pepper_robot/camera/depth_registered_metric
/pepper_robot/camera/depth_registered_rectify_depth
/pepper_robot/camera/depth_registered_sw_metric_rect
/pepper_robot/camera/front_rectify_color
/pepper_robot/camera/ir_rectify_ir
/pepper_robot/camera/points_xyzrgb_hw_registered
/pepper_robot/camera/points_xyzrgb_sw_registered
/pepper_robot/camera/register_depth_front
/pepper_robot/pose/pose_controller
/pepper_robot/pose/pose_manager
/rosout
```

### CODE REVIEW

**Comment by kochigami** [comment]
I modified this in accordance with the change of  ros-naoqi/naoqi_driver#81 .
Travis test fails because this requires the pull-request.

**Comment by nlyubova** [comment]
+1 @suryaambrose ?

**Comment by mikaelarguedas** [comment]
Note: the test is failing with this modification to the launchfile

**Comment by nlyubova** [comment]
right, @mikaelarguedas what should we do with these both requests? should we finish it or leave?

**Comment by mikaelarguedas** [comment]
This PR is fine, but the "namespace" argument should be added to [naoqi_driver.launch](https://github.com/ros-naoqi/naoqi_driver/blob/88d83cbc926299652781d4b637567cbbed2fc7cb/launch/naoqi_driver.launch) that currently doesn't know expose this argument

**Comment by kochigami** [comment]
same comment as https://github.com/ros-naoqi/naoqi_driver/pull/81

**Pull request closed without merging**
