### PR TITLE
Adding pepper_dcm_control package

### PR DESCRIPTION
**Pull request by nlyubova**
is needed for pepper_gazeb_plugin and to control the robot with MoveIt

### CODE REVIEW

**Comment by nlyubova** [comment]
@mikaelarguedas do you agree ?

**Comment by k-okada** [comment]
Just out of curiosity, what does dcm stands for?

2016年6月27日月曜日、Natalia Lyubovanotifications@github.comさんは書きました:

> @mikaelarguedas https://github.com/mikaelarguedas do you agree ?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ros-naoqi/pepper_robot/pull/22#issuecomment-228781832,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAeG3NZPNoYe9PHsXF4TvfrETRxcuTNHks5qP-zYgaJpZM4I-4Lb
> .

## 

## 

◉ Kei Okada

**Comment by mikaelarguedas** [comment]
@nlyubova I think this should be in a separate repository as it is for Nao given that people wanting to use the basic stack don't necessarily want naoqi SDK dependant packages in their workspace.
 @k-okada DCM stands for Device Communication Manager. this module manages communication at the low level in naoqi. Most of the interface to dcm is now provided by the naoqi bridge. more info here if you're interested http://doc.aldebaran.com/2-1/naoqi/sensors/dcm.html

**Comment by nlyubova** [comment]
@mikaelarguedas do you think we should place it to "pepper_virtual" similar to "nao_virtual"? or what is the best way? I have placed it here as it was for Romeo robot and I though we should have smth similar among the robots, non?

**Pull request closed without merging**
