### PR TITLE
use bottom and top for pepper's camera

### PR DESCRIPTION
**Pull request by kochigami**
i think top/bottom is camera name for pepper robot, although I can not find english information... -> http://www.bril-usa-blog.com/2015/03/pepper.html

cc: @k-okada

### CODE REVIEW

**Comment by vrabaud** [comment]
@Karsten1987 , that seems right no ?

**Comment by Karsten1987** [comment]
Can we close this PR ?

**Comment by vrabaud** [comment]
@Karsten1987  , please copy paste the same thing roughly in here: https://github.com/ros-naoqi/pepper_robot/blob/master/pepper_bringup/launch/pepper_full_py.launch

**Comment by vrabaud** [comment]
the new bridge provides all cameras

**Pull request closed without merging**
