### PR TITLE
[pepper_bringup/package.xml] add naoqi_pose, naoqi_driver_py to run_depend

### PR DESCRIPTION
**Pull request by furushchev**
- [pepper_bringup/package.xml] add naoqi_pose, naoqi_driver_py to run_depend
- [pepper_bringup/CMakeLists.txt] add test for launch file validation

Now you can check launch file validity.
e.g.  typo in launch file, missing close tag, missing to add dependencies to run_depend by
`catkin run_tests pepper_bringup -i -v`

### CODE REVIEW

**Comment by furushchev** [comment]
example output is below:

``` bash
catkin run_tests pepper_bringup -i -v
==> Expanding alias 'run_tests' from 'catkin run_tests pepper_bringup -i -v' to 'catkin build --verbose --catkin-make-args run_tests -- pepper_bringup -i -v'
-------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/leus/ros/indigo_parent/devel:/opt/ros/indigo
Workspace:                   /home/leus/ros/indigo
Source Space:       [exists] /home/leus/ros/indigo/src
Build Space:        [exists] /home/leus/ros/indigo/build
Devel Space:        [exists] /home/leus/ros/indigo/devel
Install Space:     [missing] /home/leus/ros/indigo/install
DESTDIR:                     None
-------------------------------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
-------------------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: run_tests
Internal Make Job Server:    True
-------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------------------------------
Found '277' packages in 0.5 seconds.
Starting ==> pepper_bringup
[pepper_bringup] ==> '/home/leus/ros/indigo/build/pepper_bringup/build_env.sh /usr/bin/make cmake_check_build_system' in '/home/leus/ros/indigo/build/pepper_bringup'
[pepper_bringup] <== '/home/leus/ros/indigo/build/pepper_bringup/build_env.sh /usr/bin/make cmake_check_build_system' finished with return code '0'
[pepper_bringup] ==> '/home/leus/ros/indigo/build/pepper_bringup/build_env.sh /usr/bin/make run_tests --jobserver-fds=3,5 -j' in '/home/leus/ros/indigo/build/pepper_bringup'
[pepper_bringup] Scanning dependencies of target clean_test_results_pepper_bringup
[pepper_bringup] Scanning dependencies of target tests
[pepper_bringup] Built target tests
[pepper_bringup] Removing test result files from '/home/leus/ros/indigo/build/pepper_bringup/test_results/pepper_bringup'
[pepper_bringup] Built target clean_test_results_pepper_bringup
[pepper_bringup] Scanning dependencies of target _run_tests_pepper_bringup_roslaunch-check_launch
[pepper_bringup] -- run_tests.py: execute commands
[pepper_bringup]   /usr/bin/cmake -E make_directory /home/leus/ros/indigo/build/pepper_bringup/test_results/pepper_bringup
[pepper_bringup]   /opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o /home/leus/ros/indigo/build/pepper_bringup/test_results/pepper_bringup/roslaunch-check_launch.xml /home/leus/ros/indigo/src/pepper_robot/pepper_bringup/launch
[pepper_bringup] checking *.launch in directory /home/leus/ros/indigo/src/pepper_robot/pepper_bringup/launch
[pepper_bringup] checking /home/leus/ros/indigo/src/pepper_robot/pepper_bringup/launch/pepper_full.launch
[pepper_bringup] checking /home/leus/ros/indigo/src/pepper_robot/pepper_bringup/launch/pepper_full_py.launch
[pepper_bringup] ...writing test results to /home/leus/ros/indigo/build/pepper_bringup/test_results/pepper_bringup/roslaunch-check_launch.xml
[pepper_bringup] FAILURE:
[pepper_bringup] [/home/leus/ros/indigo/src/pepper_robot/pepper_bringup/launch/pepper_full_py.launch]:
[pepper_bringup] pper_brMissing package dependencies: pepper_bringup/package.xml: naoqi_driver_py
[pepper_bringup] wrote test file to [/home/leus/ros/indigo/build/pepper_bringup/test_results/pepper_bringup/roslaunch-check_launch.xml]
[pepper_bringup] -- run_tests.py: verify result "/home/leus/ros/indigo/build/pepper_bringup/test_results/pepper_bringup/roslaunch-check_launch.xml"
[pepper_bringup] Built target _run_tests_pepper_bringup_roslaunch-check_launch
[pepper_bringup] Scanning dependencies of target _run_tests_pepper_bringup_roslaunch-check
[pepper_bringup] Built target _run_tests_pepper_bringup_roslaunch-check
[pepper_bringup] Scanning dependencies of target _run_tests_pepper_bringup
[pepper_bringup] Built target _run_tests_pepper_bringup
[pepper_bringup] Scanning dependencies of target run_tests
[pepper_bringup] Built target run_tests
[pepper_bringup] <== '/home/leus/ros/indigo/build/pepper_bringup/build_env.sh /usr/bin/make run_tests --jobserver-fds=3,5 -j' finished with return code '0'
Finished <== pepper_bringup [ 7.5 seconds ]
[build] Finished.
[build] Runtime: 9.0 seconds
```

**Comment by k-okada** [comment]
+1

**Comment by furushchev** [comment]
enabled and passed test

**Comment by furushchev** [comment]
Please merge this PR if there is no problem, and release as debian package.

**Comment by k-okada** [comment]
ok, merged, but I have no permission to send to papper_robot-release
@vrabaud @Karsten1987

**Comment by vrabaud** [comment]
Sorry for the big delay. @k-okada , you are now an owner.
Thx for the contribution, making a release.

**Pull request merged**
