### PR TITLE
Incomplete Gazebo pkg

### PR DESCRIPTION
**Pull request by 130s**
**DO NOT MERGE yet**

I ran out of my time to finish this, but I rather share my incomplete work hoping this will give some clue for someone who're interested in making Gazebo package, or she can simply take over this commit.
Problem I'm seeing is reported [here](http://answers.gazebosim.org/question/12064/model-collapses-when-physics-is-on/).

### CODE REVIEW

**Comment by vrabaud** [comment]
@keulYSMB , FYI.
@130s , should that be its own repo ?

**Comment by mikaelarguedas** [comment]
@vrabaud  Yes I answered on the gazebo answers thread directly. It seems that we're encontering the same issue. Do you know if there is any simulated version of pepper in webots or other simulator ?

**Comment by k-okada** [comment]
hi, I'm trying on running simulated version of pepper on choreographe , with small(?) modification, it runs very nicely.

see 
https://github.com/ros-naoqi/naoqi_driver/issues/54
and my workaroud version can be found at here
https://github.com/k-okada/naoqi_driver/commits/master

BTW, could you paste link to the gazebo answer thread?

**Comment by mikaelarguedas** [comment]
Hi, thanks for the fast reply. 
Sorry I should have been more precise in my question. I think that the inertia values for some links are not right and make the physics engine explode at some point. So I'm looking to see if somebody successfully simulated pepper model using the inertias from the URDF (using a classic physics engine s.t. ODE or bullet).

[Here](http://answers.gazebosim.org/question/12064/model-collapses-when-physics-is-on/) is the link to the question asked by 130s

**Comment by vrabaud** [comment]
@keulYSMB, Pepper has probably been  Webots but just like NAO, it's not with accurate physics, and not based on those URDFs.

**Comment by vrabaud** [comment]
@130s, when can we merge that ? thx for your work btw !

**Comment by 130s** [comment]
I'm not foreseeing in the next several weeks that I can get to work on this. I'm happy to let someone else take the commit over (or I don't mind discarding this and someone starts new work).

> should that be its own repo ?

Hmm, why not consolidate more packages into a fewer repositories? Just an idea:

```
pepper
|-  pepper_robot
|-  pepper_gazebo
|-  pepper_moveit_config
```

**Comment by k-okada** [comment]
taken over by https://github.com/ros-naoqi/pepper_virtual

**Pull request closed without merging**
