### PR TITLE
fixing bugs in wheels

### PR DESCRIPTION
**Pull request by nlyubova**
@mikaelarguedas could you please look at it?
It was missing before, but still wheels do not work like they should do. Do you see where is the mistake? fdir ? mu?

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
didn't have time to look into it yet but will try to inverstigate a bit tomorrow.
Two surprising things a the first look: 
- the `pepper_robot` namespace, the controllers are defined in the `pepper_dcm` namespace (https://github.com/ros-naoqi/pepper_virtual/blob/master/pepper_control/config/pepper_trajectory_control.yaml#L1)
- the fdir definition shouldnt be multi axis

**Comment by mikaelarguedas** [comment]
@nlyubova please avoid `push -f` on pull requests because the comments on the original commit are lost. You can squash all your commits into a single one just before merging

**Comment by nlyubova** [comment]
@mikaelarguedas thanks, need your +1 to merge it. The namespace was a mistake, it should be empty like it was before (this is the only way to make it working with MoveIt controllers). 

fdir is not a milti axis anymore.

**Comment by mikaelarguedas** [comment]
Code looks good to me but I didn't have time to test it yet :disappointed:. if you tested it thoroughly locally, you can merge it and I'll test it from master as soon as possible.
Thanks!

**Review by mikaelarguedas — APPROVED** [review]

**Comment by nlyubova** [comment]
thanks! it does not crash, but still wheels do no work like they should

**Comment by kochigami** [comment]
Hi, 
instead of using libgazebo_ros_diff_drive.so, I tried libgazebo_ros_planar_move.so with this change and the code before this change.
Even though pepper moves  x, y direction and rotates, pepper was falling down as this said: 
http://answers.ros.org/question/212889/gazebo-planar-move-plugin-for-omni-directional-wheel/

screenshot from 2016-10-06 15 26 51

As for libgazebo_ros_planar_move.so, 
it seems that there is no difference between this change and the codes before this change.

I also tried libgazebo_ros_force_based_move.so (gained by `sudo apt-get install ros-indigo-hector-gazebo-plugins`) instead of libgazebo_ros_planar_move.so, but it caused an error.

If anyone knows how to avoid falling down of pepper caused by  libgazebo_ros_planar_move.so,
could you help me?

What I used is this:

```
<gazebo>
  <plugin name="planar_move_controller" filename="libgazebo_ros_planar_move.so">
    <commandTopic>cmd_vel</commandTopic>
    <odometryTopic>odom</odometryTopic>
    <odometryFrame>odom</odometryFrame>
    <odometryRate>20.0</odometryRate>
    <robotBaseFrame>base_footprint</robotBaseFrame>
  </plugin>
</gazebo>
```

**Comment by nlyubova** [comment]
Did you try different speed? And changing wheel fraction, mu1 and mu2? To prevent sliding

**Comment by nlyubova** [comment]
By chance, did you check gazebo_ros_force_based_move plugin?

**Comment by kochigami** [comment]
@nlyubova 
Thank you very much for your comment.

> Did you try different speed? And changing wheel fraction, mu1 and mu2? To prevent sliding

I didn't do that. I'll try it next. Thank you very much.

> By chance, did you check gazebo_ros_force_based_move plugin?

Yes, I followed the comment in http://answers.ros.org/question/212889/gazebo-planar-move-plugin-for-omni-directional-wheel/.
However, the error like this occurred. I didn't know how to use it.

```
<gazebo>
  <plugin name="force_based_move_controller" filename="libgazebo_ros_force_based_move.so">
    <commandTopic>cmd_vel</commandTopic>
    <odometryTopic>odom</odometryTopic>
    <odometryFrame>odom</odometryFrame>
    <odometryRate>20.0</odometryRate>
    <robotBaseFrame>base_footprint</robotBaseFrame>
    <publishOdometryTf>0</publishOdometryTf>
    <yaw_velocity_p_gain>10000000.0</yaw_velocity_p_gain>
    <x_velocity_p_gain>10000000.0</x_velocity_p_gain>
    <y_velocity_p_gain>10000000.0</y_velocity_p_gain>
  </plugin>
</gazebo>
```

```
Segmentation fault (core dumped)
[gazebo-2] process has died [pid 24713, exit code 139, cmd /opt/ros/indigo/lib/gazebo_ros/gzserver -u -e ode /home/kochigami/catkin_ws/src/pepper_virtual/pepper_gazebo_plugin/worlds/naoFoot.world __name:=gazebo __log:=/home/kochigami/.ros/log/b8da093e-8c47-11e6-890c-507b9d20c4fb/gazebo-2.log].
log file: /home/kochigami/.ros/log/b8da093e-8c47-11e6-890c-507b9d20c4fb/gazebo-2*.log
```

Sorry, I couldn't help you. I'll keep looking into it.

**Comment by nlyubova** [comment]
@kochigami thank you for your comments. I've just tested  the planar_move plugin and you are right that it makes the robot fall to one side. If you replace base_footprint to base_link, it is a bit better but still the robot falls to one side. will try to fix it. Please, Let me know if you find a solution

**Comment by fqez** [comment]
Hi! I'm having the same falling problem. What is the state of this PR? This one solve the Pepper falling problem?

**Comment by nlyubova** [comment]
Hi, no unfortunately it does not

**Pull request merged**
