### PR TITLE
update to the latest alrobotmodelutils

### PR DESCRIPTION
**Pull request by vrabaud**
@Karsten1987 , have fun :)
I know some files have not changed and have only been re-ordered but that's how it's exported so we should probably accept those changes.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
LGTM, it seems they just updated some naming conventions

**Comment by vrabaud** [comment]
for naming, I am the one who updated "joint" to "fixedjoint" for the optical_frame and I added a device frame for the lasers (and contributed fixes to the position as done in https://github.com/ros-naoqi/naoqi_bridge/blob/master/naoqi_tools/scripts/generate_urdf.py#L157

**Comment by mikaelarguedas** [comment]
I was refering to the name of the robot who gained a capital letter (which has no impact at all). But yeah I didn't notice the lasers.  Nice, thanks for fixing it!

**Comment by Karsten1987** [comment]
I am a bit confused about the front lasers.

SurroundingFrontLaser_device_frame,
ShovelLaser_frame,
VerticalLeftLaser_frame,
VerticalRightLaser_frame

are all place in the same position and orientatin https://github.com/vrabaud/pepper_robot/blob/master/pepper_description/urdf/pepper1.0_generated_urdf/pepper_sensors.xacro#L36

is that on purpose?

**Comment by mikaelarguedas** [comment]
If I remember well, in pepper documentation, the actual laser position are given by SurroundingLeft SurroundingRight and SurroundingFront.
I think that Shovel and Vertical lasers are artefacts (still published by almodelutils) from the older pepper version when the projector and receptor were not at the same place.
I don't have access to the documentation anymore, can any of you confirm that?

**Comment by vrabaud** [comment]
You can use this script to compare the .xacro folders: https://github.com/ros-naoqi/naoqi_bridge/blob/master/naoqi_tools/scripts/compare_xacro.py

**Comment by Karsten1987** [comment]
The RightLaser_device_frame is incorrect. The x-coordinate should be equal to the x-coordinate of the RightLaser_frame

device frame:
https://github.com/vrabaud/pepper_robot/blob/master/pepper_description/urdf/pepper1.0_generated_urdf/pepper_sensors.xacro#L85
laser frame:
https://github.com/vrabaud/pepper_robot/blob/master/pepper_description/urdf/pepper1.0_generated_urdf/pepper_sensors.xacro#L127

**Comment by vrabaud** [comment]
thx, fixed in https://github.com/ros-naoqi/naoqi_bridge/commit/a74f895c8869aac9022b785142a5ff55cef8acc5

**Comment by vrabaud** [comment]
and updated the PR

**Pull request merged**
