### PR TITLE
Fix namespace to avoid duplication and node name empty #35

### PR DESCRIPTION
**Pull request by PacoDu**
Related to #35 and [naoqi_driver PR #85](https://github.com/ros-naoqi/naoqi_driver/pull/85)

### CODE REVIEW

**Comment by nlyubova** [comment]
@suryaambrose followed the merged PR in Naoqi Driver, should merge this one?

**Comment by jokla** [comment]
I confirm that these modifications are necessary under Ubuntu 16.04 and ROS Kinetic. Otherwise, the depth and point cloud don't work.

**Comment by kochigami** [comment]
+1

I confirmed it under Ubuntu 14.04 and ros indigo.

**Comment by nlyubova** [comment]
@suryaambrose what do you think? 
+1 from me

**Comment by suryaambrose** [comment]
ok for me !

**Comment by Karsten1987** [comment]
@nlyubova @suryaambrose 
Could one of you test this again and finally merge it?

**Comment by nlyubova** [comment]
@PacoDu could you please git pull and rebase?

**Comment by mikaelarguedas** [comment]
@nlyubova @suryaambrose  What is the status on this ?

**Pull request merged**
